services:
  app:
    build: .
    container_name: avatar-idt
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      URL_REDIS: redis://host.docker.internal:6379
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
